#!/usr/bin/env perl

use strict;
use warnings;
use File::Basename 'dirname';
use Cwd;
BEGIN{
  $ENV{MOJO_MODE} ||= 'development';
  #$ENV{MOJO_MODE} = 'production';
  #$ENV{MOJO_HOME} ||= Cwd::abs_path(dirname(__FILE__));
  $ENV{MOJO_HOME} ||= '/var/www/timerec';
}

use lib ( "$ENV{MOJO_HOME}/lib");
#use lib ( "/var/www/timerec/lib");



# Application
$ENV{MOJO_APP} = 'AproJo';
$ENV{TIMEREC_CONFIG} = "$ENV{MOJO_HOME}/timerec.conf";

require Mojolicious::Commands;
Mojolicious::Commands->start_app('AproJo');

__END__


