#!/usr/bin/env perl

use strict;
use warnings;

use Data::Dumper;

use File::Basename 'dirname';
use File::Spec::Functions qw(catdir splitdir);

BEGIN{
  $ENV{MOJO_MODE} ||= 'development';
  #  $ENV{MOJO_MODE} = 'production';
  $ENV{MOJO_HOME} ||= '/var/www/AproJo';
}

# Source directory has precedence
my @base = (splitdir(dirname(__FILE__)), '..');
my $lib = join('/', @base, 'lib');
-e catdir(@base, 't') ? unshift(@INC, $lib) : push(@INC, $lib);

#use lib ( "$ENV{MOJO_HOME}/lib", "/home/helmutw/github/Mojolicious-Plugin-Form/lib");

#print STDERR '@INC: ',Dumper(\@INC),"\n";

$ENV{MOJO_APP} ||= 'AproJo';

# Start commands for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('AproJo');

__END__
